apiVersion: v1
kind: Service
metadata:
  name: dnb-app-image
  labels:
    app: dnb-app-image
    deploymentconfig: dnb-app-image
spec:
  ports:
  - name: web
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: dnb-app-image
    deploymentconfig: dnb-app-image
  type: ClusterIP
